### ISSUE TITLE
Last updated date on documentation search results is always today

### ISSUE THREAD

**Issue by ed-parry** [umbraco/OurUmbraco#251] opened 2018-06-07 19:22 UTC
Here's an [example](https://our.umbraco.org/search?q=search&cat=documentation) - each result has today's date as the last updated value, with a blank space for the created date. Looks to be related to #245 but I guess this is an overhang of standard search functionality that doesn't yet apply/work for the documentation pages?

**Comment by nul800sebastiaan** [comment] 2018-06-07 19:45
Yeah, I'll close it as a dupe of #245 - there's no way we can currently get the real last updated date.

**Closed by nul800sebastiaan** 2018-06-07 19:45 UTC

**Comment by ed-parry** [comment] 2018-06-07 20:30
@nul800sebastiaan Makes sense. Is it worth a quick PR to remove the dates from the documentation search results then, or very low priority for now? Can be confusing when documentation results appear alongside forum posts in results.

**Comment by nul800sebastiaan** [comment] 2018-06-07 21:03
Neh, not after being there for years ;-)
