### ISSUE TITLE
Breadcrumb link "member" returns 404

### ISSUE THREAD

**Issue by fALKENdk** [umbraco/OurUmbraco#506] opened 2019-11-04 08:40 UTC
Breadcrump link Member on the profiles page returns 404, it links to `https://our.umbraco.com/member/` which does not exists and should link to the users own profile.

Steps to reproduce:
`https://our.umbraco.com/members/falkendk/` click on `Member` in the breadcrumb.

**Comment by erikjanwestendorp** [comment] 2020-01-11 17:22
Hi 

This it’s a bit weird behavior indeed. It seems that the issue is in the [BreadcrumbController](https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco/Our/Controllers/BreadcrumbController.cs) / [breadcrumb.cshtml](https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco.Site/Views/Partials/Global/Breadcrumb.cshtml ) view. 

The CurrentPage will be added to the breadcrumb but the querystring is missing. A quick and dirty fix could be:

    @model List<IPublishedContent>
    @{
        var currentUrl = Request.Url?.AbsolutePath;
    }
    <ul id="breadcrumb">
        <li>
            <a href="/">Our</a>
        </li>
        @foreach (var page in Model)
        {
            if (page.ContentType.Alias == "ProjectGroup")
            {
                <li><a href="@page.Parent.Url?category=@HttpUtility.UrlPathEncode(page.Name)">@page.Name</a></li>
            }
            else if (!string.IsNullOrEmpty(currentUrl) && currentUrl.Equals(page.Url))
            {
                <li><a href="@Request.Url">@page.Name</a></li>
            }
            else
            {
                <li><a href="@page.Url">@page.Name</a></li>
            }
        }
    </ul>

**Comment by nul800sebastiaan** [comment] 2021-03-03 10:44
Closing this as it's been fixed 👍

**Closed by nul800sebastiaan** 2021-03-03 10:44 UTC
